RedHatInsights/rhc

- .github/workflows/go.yml
- Makefile
- constants.go
- go.mod
- go.sum
- main.go
This patch outputs the canonical facts with an appropriate indentation
for better readability.
Expected results:
```
$ rhc canonical-facts
{
"insights_id": "08eca62e-ee30-49c6-a96c-d8bf59a570e5",
"machine_id": "e64a070b-fdb9-139e-2586-f6ee138068b5",
"bios_uuid": "2a362d74-d64e-4be5-aaf8-daa758d052f4",
"subscription_manager_id": "a5c5f1e1-c117-4a55-93c3-bc361353e9b6",
"ip_addresses": [
"192.168.0.28"
],
"mac_addresses": [
"52:54:00:78:d4:02",
"00:00:00:00:00:00"
],
"fqdn": "rhel84.strider.local"
}
```
Signed-off-by: Gael Chamoulaud (Strider) <gchamoul@redhat.com>
> [canonical-facts] Display output as pretty formatted JSON

- go.mod
- go.sum
Summary
Downgrade the spinner library to fix a rendering bug. See briandowns/spinner#123.
With spinner v1.16.0:
With spinner v.1.13.0:
Signed-off-by: Gael Chamoulaud (Strider) <gchamoul@redhat.com>
> Fix rendering bug where the spinner doesn't erase its loading message

- insights.go
- main.go
- rhc.spec.in
Introduce `insights-client` as an explicit step during the `connect` and `disconnect` subcommands. During `connect`, the process shells out to, and waits for, `/usr/bin/insights-client --register` to execute successfully. Conversely, during `disconnect`, the process shells out to and waits for `/usr/bin/insights-client --unregister` to execute successfully. In addition, the `insights-client --status` exit code is checking during the `status` subcommand execution.
> Include insights-client during "connect" and "disconnect"

- go.mod
- go.sum
In commit [1], we've had to downgrade that package due to a rendering
bug[2]. This latter has been fixed upstream[3] and released in the v1.17.0[4].
We can now 'revert' the downgrade to v1.13.0 by upgrading directly to
the v1.17.0.
[1] https://github.com/RedHatInsights/rhc/pull/5/commits/2ed9d23e087958481ee5aa7675cd5b899dcd7f8e
[2] https://github.com/briandowns/spinner/issues/123
[3] https://github.com/briandowns/spinner/pull/126
[4] https://github.com/briandowns/spinner/releases/tag/v1.17.0
Test done with the v1.17.0:
> fix: Upgrade github.com/briandowns/spinner to v1.17.0

- .copr/Makefile
- .copr/rhc.spec.in
- .gitignore
- Makefile
As part of the decoupling of `rhc` and `yggdrasil`, we need to stitch things back together when building the `rhc` RPM. This PR modifies the spec file that is built in COPR to include `yggdrasil` and `yggdrasil-worker-package-manager` as secondary sources, builds them and includes them in the resulting RPM.
> Bundle yggdrasil and yggdrasil-worker-package-manager

- canonical_facts.go
The package io/ioutil was deprecated and the CI complained about
that. More detail could be found here: https://go.dev/doc/go1.16#ioutil
> fix: Do not use deprecated io/ioutil

- .github/workflows/go.yml
Do not test Go version 1.15, because it is not used by any supported RHEL (7,8,9). The RHEL7 uses version 1.17.
> feat: Drop version of GO 1.15 from CI testing

- insights.go
- main.go
* When insights-client is not installed, then running command is finished with `*ExitError` and it is not possible to check state of the process
> Bug fix: check result of running command

- main.go
- util.go
* When `stdout` is not TTY, then do not display spinner and status text and the output of `rhc` should not be colorful, because output is redirected to some file. When temporary status messages and escape sequences were added to log file, then viewing such file could be complicated.
* When `NO_COLOR` environment variable is set, then do not display color nor animation too.
* This commit closes #14 issue
> feat: Better support for non-interactive mode

- main.go
- register.go
* Functions of sub-commands were moved to function outside of main function. Created several functions to not duplicate code. Side effect of this effort is better displaying of errors for "connect" sub-command.
* Functions for "main" and "before" actions were also move outside main function
* Fixed one small issue with registration to RHSM. It is possible to use --organization, when --username and --password are specified. The registration process could be improved more, but it should be part of another commit. Added only fix-me comment for this case.
> feat: Big refactoring of main.go

- go.mod
- main.go
* Sub-command status has now --json option. When this option is used, then status is printed to stdout at JSON document.
* JSON document always contains following items:
- hostname
- rhsm_connected
- insights_connected
- rhcd_running
* When something goes wrong, then JSON document can contain addition following items:
- hostname_error
- rhsm_error
- insights_error
- rhcd_error
* Example of JSON output can look like this:
```
[root@rhel9 ~]$ rhc status --json
{
"hostname": "rhel9",
"rhsm_connected": true,
"insights_connected": false,
"insights_error": {
"Op": "fork/exec",
"Path": "/usr/bin/insights-client",
"Err": 2
},
"rhcd_running": false
}
```
> feat: Add --format json option for status sub-command

- main.go
* When non-root user tries to connect or disconnect system, then print error message and return exit code 1
* Note: it is still possible to run status sub-command as non-root user
> fix: better messages, when non-root user tries to (dis)connect

- register.go
When registering with username & password, include "enable_content" in the options map to ensure content gets enabled.
Fixes: RHBZ#2141454
> Enable content when registering with username & password

- README.md
- main.go
RHC stands for Remote Host configuration, change all old mentions to this acronym to meet this name.
Resolves: ESSNTL-4228
> feat: rhc renaming

- main.go
* When you want to connect system against Satellite, then it is not possible to simply run on freshly installed  RHEL system:
`rhc connect --server satellite.company.com`
It just cannot work. Why? Using satellite server requires more changes in `rhsm.conf` (e.g. `base_url`). It requires installing CA cert and potentially something else (proxy). All required changes are typically done by kickstart script during installation of RHEL or you can use bootstrap script provided by Satellite server.
* The --server CLI option could be still used for testing against stage environment, but it is useless for our customers. For this reason it is kept as hidden option.
> feat: Make --server CLI option hidden

- internal/http/client.go
- main.go
HTTPClient was setting a custom transport instead of using the Default, leading to a unconfigured proxy from environment variables.
This commit modifies the default transport to use the proxy env variables.
Resolves: [RHBZ#2223405](https://bugzilla.redhat.com/show_bug.cgi?id=2223405)
> fix: http proxy configuration

- main.go
- util.go
This commit fixes the exit status when `rhc` fails to retrieve the system profile. When `rhc` cannot retrieve the profile it will debug this failure, but the execution will fail without any error.
`rhc` should not end with a 1 status if it is connected to `rhsm` and `insights`.
old `rhc` output:
```
rhc connect
Connecting localhost.localdomain to Red Hat.
This might take a few seconds.
● Connected to Red Hat Subscription Management
● Connected to Red Hat Insights
● Activated the Remote Host Configuration daemon
Successfully connected to Red Hat!
Manage your connected systems: https://red.ht/connector
The following errors were encountered during connect:
STEP                       ERROR  
Remote Host Configuration  Cannot get the user profile: Get …
```
> fix: not end with an error when retrieving the system profile

- Makefile
* It is possible to build rhc using `make`
* It is also possible to clean repository using `make clean`, when some generated file has been already deleted.
> fix: Fix building "rhc" using make

- .github/workflows/go.yml
* Drop Go 1.16 from testing matrix
* Added Go 1.20 to the same matrix
* Note: The RHEL7.9 uses Go 1.19 and the latest Fedora uses 1.20
> fix: Update testing matrix

- rhc.bash
* Card ID: RHELPLAN-164718
* Checking of issues using shell script analysis tool shellcheck should be without any issue now.
* Note: current version of bash auto-complete script provided by urfave package looks little bit different, but it is not compatible with rhc for some reason.
> fix: Fix issues of bash auto-complete script

- main.go
This commits fixes the insights-connection status when it is not connected.
Now it shows false when printing in the json format.
> fix: insights connection status

- .copr/rhc.spec.in
- go.mod
This commit:
- Updates go version to 1.18
- Add systemd as a BuildRequirement
This is meant to fix current COPR builds.
Resolves: CCT-61
> build: update go version

- go.mod
- go.sum
* Dependabot opened two issues related to yaml module:
* https://github.com/RedHatInsights/rhc/security/dependabot/6
* https://github.com/RedHatInsights/rhc/security/dependabot/5
* Dependabot was not able to create PR automatically for some unknown reason
* This commit should fix them both
> fix: Upgrade yaml module to version v2.4.0

- .copr/Makefile
- .copr/rhc.spec.in
- Makefile
- README.md
- activate.go
- constants.go
- main.go
- status.go
Code cleanup before fixing RHEL-2490
* Split `statusAction` to several logical functions and moved
these functions to new new file `status.go`
* Refactored getting user interface preferences
* Previous management was confusing
* Upstream name of the service is `yggdrasil`, but upstream
version of `rhc` used default branded name `rhcd` from downstream
for this service. Thus, it was not possible to use
upstream version of `rhc` for activating/deactivating
of upstream version of `yggdrasil`.
* Brand name was not brand name of `rhc`, but it was used
for branding of service name.
* The service name was assembled from short name of `rhc`.
`rhc + "d.service"`. Thus, it actually was not possible to
brand the service.
* Removed `BrandName` and introduced `ServiceName` and `SERVICENAME`
constants. …
> Refactoring of status command and rhcd service

- .github/workflows/go.yml
- .github/workflows/lint.yml
* When PR was created or updated, then all jobs releated to Go were triggered twice. Not useful and wasting of time and resources
* Added workflow_dispatch to be able to trigger workflows manually
> fix: Do not trigger build go actions twice on PR

- register.go
- util.go
* It is important to call all RHSM D-Bus methods with some locale string, because candlepin server generates some error string, and candlepin server has localized these error messages. Thus, candlepin server needs to know locale string to generate error messages properly.
* All methods were called with locale hardcoded to "". It means that error messages could not be localized according users' preferences.
* Locale string is get from environment variable $LANG.
> fix: Set locale in all D-Bus RHSM calls according LANG env. var.

- main.go
- status.go
This patch simplifies the way we handle and display status information about individual things rhc tracks.
1/ Message icons
Colors, icons and statuses were simplified. The (red) state of    'disconnected' was removed and was replaced by error/info depending on the context (e.g. 'status' reports disabled yggdrasil/rhcd at 'info' level; it is a valid state for some customer setups, it should not be in red).
2/ Message colors
Blue (info) color was switched for yellow, which is more common for green (ok) - info - error (red) scheme.
3/ Representation of the preference data
`UserInterfacePreferences` struct was replaced by `userInterfaceSettings`, which is set up once as a global variable `uiSettings` and is reused throughout the code, instead of being re-computed multiple times throughout the …
> feat: Better handling of colors and icons

- .copr/Makefile
- .copr/rhc.spec.in
Make use of yggdrasil and the package manager worker as available from the system, rather than bundling static versions of them.
This makes it possible to build & use rhc against development versions of them.
> build: unbundle yggdrasil & worker-package-manager

- go.mod
- go.sum
- util.go
I've moved go-ini to github, hopefully to facilitate external contributors. Update rhc to use the package hosted on github.
> Update go-ini import path

- go.mod
- go.sum
- main.go
- util.go
Update to github.com/subpop/go-log.
This change was motivate because of SourceHut service and its stability. We also change the go-ini to github https://github.com/RedHatInsights/rhc/pull/81
> refactor: update go-log path

- insights.go
- main.go
- status.go
* Card ID: CCT-288
* When "rhc status" is run as non-root user, then status about insighst-client should not tell that insights-client is not registered.
* When "rhc status" is run by non-root user, then rhc prints decent error about insights client. It prints: "Insights client must be run as root."
* Also fixed the case, when status command is run with "--format json". When some error happens, then generated JSON contains real error message and not empty dictionary.
> fix: Print correct error, when non-root user run "rhc status"

- util.go
* When it is not possible to read or parse configuration file /etc/insights-client/insights-client.conf, then display error message containing path to this configuration file
> feat: Improve error messages, when reading insights-client.conf

- rhc.spec.in
* yggdrasil is not required for building, but it is required for proper working of rhc client
> fix: Do not require yggdrasil for building

- integration-tests/test_connect.py
- integration-tests/utils/__init__.py
- Upstream name of the service is changed from rhcd to yggdrasil, so replacing the service name from rhcd to yggdrasil in tests also.
Ref: https://github.com/RedHatInsights/rhc/pull/53
> fix(test):Refactoring to replace service name from rhcd to yggdrasil

- .packit.yml
This way we can track the cloud costs for the team and also provide more detailed team specific metrics.
> packit: tag cloud resources in Testing Farm

- systemtest/copr-setup.sh
Running Pr jobs downstream fails because sometimes beaker composes dont have client tools installed, by adding this rhc install it will help mitigate dependency issues.
> fix: fixed rhc dependency issue for downstream PR testing

- integration-tests/conftest.py
- integration-tests/test_connect.py
- integration-tests/test_man_page.py
- integration-tests/utils/__init__.py
Currently, running these tests downstream fail because the name of service is still rhcd in downstream package. As a fix I have added variable to identify the name of service and perform verification accordingly.
> fix(test): Updated tests to run for rhcd downstream

- systemtest/tests/integration/test.sh
Saving the test report as a junit file.  This will also fix failing rhc jenkins tests since they're now expecting a junit.xml
> feat: Saving test report as junit file

- main.go
- status.go
* It is possible to print output of disconnect command in machine-readable format. The --format requires argument and it could be only "json" ATM. It follows practice of status command.
* Refactored code a little to share some code with status command.
> feat: Add CLI option --format to disconnect command

- integration-tests/test_status.py
One test currently fails due to known issue :https://issues.redhat.com/browse/CCT-525
> test: Added tests for rhc status

- main.go
* It is possible to run connect command with CLI option
`--format json`. The output of connect command is in machine
readable format in such case.
> feat: Add --format json for connect command

- main.go
- status.go
* When some sub-status is not correct (system is not registered, insights-client is not registered or yggdrasil is not running), then return non-zero status code
* This change follow behavior of subscription-manager and it could help automation
> fix: Return non-zero code, when some sub-status is wrong

- integration-tests/test_status.py
* The returned value is non-zero, when some sub-task returns non-zero value. This change was introduced in this PR: https://github.com/RedHatInsights/rhc/pull/126
* We should check for non-zero code, not zero code in this case
> test: Fixed test of rhc status

- 80-rhc.preset
- Makefile
- rhc-canonical-facts.service
- rhc-canonical-facts.timer
- rhc.spec.in
In order to correctly identify a yggd instance to console.redhat.com,
yggd needs to be told where to get canonical-facts. This timer writes
the output of canonical-facts to a path where yggd can be configured to
read it when it starts up.
Card ID: CCT-291
> feat: write canonical-facts file for yggd

- insights.go
- status.go
* Card ID: CCT-525
With `legacy_upload=True` mode, `insights-client --status` returns code
0 if the system is registered and 1 otherwise. In non-legacy mode, 0 is
always returned.
Even though the `/etc/insights-client/.registered` file is not a public
API, it is reliable and we should be able to use it to detect the
registration status.
> fix: Detect insights-client status in non-legacy mode

- rhc.spec.in
- Install symlink from rhcd to yggdrasil
- Install symlink from /etc/rhc/config.toml
Card ID: CCT-639
> build: Include rhc-compat subpackage

- main.go
Card ID: CCT-698
Remove functions showConfProfile and getConfProfile and the block of code that had invoked it.
> feat: Remove the RHC Manager status from rhc client

- main.go
* There were one edge case, when not only JSON document was printed to stdout, and some user input was required. This case happened, when user is member of more organizations and --organization was not specified using CLI option
* Do not print error message, when no format is specified
* When no --username/--password is specified and --format json is used, then do not ask for input, but print some error.
> fix: Printing JSON document & printing error

- .packit.yml
Factorize the existing tests blocks for centos-stream first, so adding the new version is easier.
> ci: build & test also on centos-stream-10

- main.go
* When RHSM registration failed, then machine output was corrupted, because we printed information about skipping registration using insights-client to stdout
> fix: Machine readable output corrupted, when registration fails

- main.go
- util.go
Card ID: CCT-524
The rhc subcommands, connect, disconnect and status ignore any unknown options given. This PR will fix this by returning an error when any unknown options are found.
The following tests were performed:
Test 1:  One unknown argument give.
```
% sudo  ./rhc connect activation-key 
error: unknown option(s): activation-key 
```
Test 2: Valid arguments given but unknown arguments were also given. The extra unknown
arguments will produce an error.
```
% sudo  ./rhc connect --activation-key ${MY_KEY} --organization ${MY_ORG}  bobs your uncle
error: unknown option(s): bobs your uncle 
```
> fix: Report any unknown options found on the command line.

- .packit.yml
* Do not build rhc on Centos Stream 8, because Centos Stream 8 reached EOL. The main branch also does not go to RHEL 8.
> fix: Removed Centos Stream 8 from CI testing matrix

- activate.go
* Card ID: CCT-686
* Reload context after starting or stopping yggdrasil service. When context is not reloaded, then systemctl complains about changed unit/config file and it suggest to run: `systemctl daemon-reload`
* IDE also fixed indentation
> fix: Reload context after activation of yggdrasil service

- .packit.yml
* Main branch does not go to RHEL-8. Thus, there is no need to
do CI testing on RHEL-8
> fix: Remove RHEL-8 from CI matrix for main branch

- integration-tests/test_e2e.py
This test is part of test migrations and currently fails due to open issues https://issues.redhat.com/browse/CCT-862 and https://issues.redhat.com/browse/CCT-696. Currently it is marked to skipped. we will enable it once the issues are fixed
> test: Added e2e test for rhc connect

- .github/workflows/dist.yml
Add a dist GitHub Action that builds and attaches a release tarball when a version tag is pushed.
Card ID: [CCT-1019](https://issues.redhat.com/browse/CCT-1019)
> Add dist workflow

- dist/srpm/rhc.spec.in
- Move the %global setup_flags inside the %else condition
- Drop 'pwd' and 'ls' from %build
> build(srpm): remove some uncessary commands

- activate.go
- data/systemd/80-rhc.preset
- data/systemd/meson.build
- data/systemd/rhc-canonical-facts.service
- dist/srpm/rhc.spec.in
- internal/systemd/systemd.go
- internal/systemd/systemd_test.go
- internal/systemd/testdata/simple.service
A collection of small changes to the rhc-canonical-facts service and timer. These changes are intended to ensure the timer and services run appropriately. Instead of trying to start rhc-canonical-facts.service as a requirement of yggdrasil.service, this PR changes the behavior of `rhc connect` so that first the `rhc-canonical-facts.timer` is started, followed by the `yggdrasil.service`.
This PR makes additional code run when `rhc connect` is run, so it should be testable running `rhc connect` using whichever credentials you prefer (username/password or activation-key/org-id).
No visible changes are made to the output of `rhc connect`, so to verify this PR is doing what it says, you'll need to check for the status of a few systemd units.
After successfully running `rhc connect`, check the …
> feat: Correctly start rhc-canonical-facts.timer and service

- main.go
- rhsm.go
Card ID: CCT-769.
This is dependent on [this PR](https://github.com/candlepin/subscription-manager/pull/3462), which the requirements are still being discussed, so I'm leaving this in draft for now.    
This PR implements a new option to register with a content template, given the content template name. Since content templates are implemented as environments in candlepin, I've tried to implement this such that some code could be re-used in the future for registering with environments.
Feedback is appreciated and welcome :)
Still needs
> feat: register with content templates

- data/systemd/meson.build
- data/systemd/rhcd.conf
- dist/srpm/rhc.spec.in
- meson_options.txt
- Drop the separate compat subpackage in favor of bringing the migration components into the main rhc package.
- Replace the manual symlink with a systemd drop-in file that adds an Alias=rhcd.service to yggdrasil.service.
- Detect /etc/rhc/config.toml during upgrade and copy it to the new location.
Card ID: CCT-1127
> fix(srpm): incorporate migration elements

- connect_cmd.go
- disconnect_cmd.go
- features.go
- interactive.go
- main.go
- rhsm.go
* Card ID: CCT-1005
* First step of levels of connectivity
* When connect command is used, then it is possible to
enabled or disable three features using command line
options `--enable-feature` or `--disable-feature`. Following
features are supported
- `content`
- `analytics`
- `remote-management`
* Added checks for allowed combination of CLI options
* Modified UI little bit to be able to visualize that
feature was not started
* Output to JSON format is still supported
* When machine readable format is used, then add information
about enabled/disabled content to generated JSON file
* When machine readable output is used, then list of
enabled/disable features is added to the generated JSON doc
* Unified UI for colorful and not colorful mode
* Changed UI for `disconnect` command to looks …
> feat: Added levels of connectivity to connect command

- integration-tests/test_connect.py
This test is failing due to unresolved issue CCT-696, After the issue is fixed the test might need to be rewritten also, so disabling the test unless issue is fixed.
> test: Skipping test test_rhc_worker_playbook_install_after_rhc_connect

- integration-tests/test_status.py
Name of yggdrasil daemon is rhcd in rhel 9, added check to autodetect the name of service and perform assertions as requested
> test: Updating name of yggdrasil service to rhcd in test for rhel9.

- systemtest/copr-setup.sh
rhc-compat package is no longer being built and required.
> test: Removing rhc-compat rpm install from copr-setup

- systemtest/tests/integration/test.sh
DNF commands cannot be run without special options, and our images will be pre-prepared for use in tests.
Card: CCT-1183
> test: Check for bootc/image-mode deployments

- .packit.yml
The `@yggdrasil/latest` copr is used to build rhc/main, and only for newer versions of RHEL. Since this branch only builds for RHEL 8 & 9 currently, then let's amend the packit configuration to build in the right place:
- split the jobs for PRs and commit depending on the RHEL version, as they will need to use different copr's
- use the right copr's depending on the version built
- use unique identifier to avoid conflicts
> [0.2] ci: fix packit configuration for versions & coprs

- connect_cmd.go
* When content is disabled with --disable-feature content, then --content-template CLI option cannot be used, because it does not have any sense to use content-template environment with content, when content is disabled.
> fix: Content template cannot be used, when content is disabled

- connect_cmd.go
- integration-tests/test_connect.py
- integration-tests/utils/__init__.py
* Card ID: CCT-1161
* When `--format json` is used, then all credentials has to be provided. Not only `username` & `password` has to be considered, but also `activation-key` and `organization` has to be allowed to use in such case.
* Added one more check: combination of activation-key and password should not be allowed.
> fix: Allow to use activation key(s) and org with --format json

- integration-tests/test_man_page.py
- main.go
* Card ID: CCT-1167
* Added list of featured IDs to the help of "connect" command. Thus, users will be able to find values they can use with `--enabled-feature` and `--disable-feature`
* The man page also contains allowed values now, because man page is auto-generated from source code.
* Extended integration test to include checks of new CLI options and feature IDs
* TODO: Try to add these values to bash completion script somehow, but maybe it will be possible only with higher version of urfave/cli (not v2)
> feat: Added list of features IDs to --help

- activate.go
- disconnect_cmd.go
- internal/systemd/systemd.go
- internal/systemd/systemd_test.go
- rhsm.go
* Card ID: CCt-1162
* When some feature (e.g. analytics) was disabled during
`rhc connect`, using `--disable-feature "analytics"` CLI option,
then later do not try to unregister insights-client, when
`rhc disconnect` is run. There is printed only informative
message that given "feature" has been already disconnected.
* This change also improve the case, when system is connected
using `rhc connect`, but later user run command
`insights-client --unregister`. No error should be printed
in such case.
* TODO: Fix integration tests
* When you run `rhc disconnect` multiple times, then output
looks like this:
```
root@localhost:/# rhc disconnect
Disconnecting localhost from Red Hat.
This might take a few seconds.
[●] The yggdrasil service is already inactive
[●] Already disconnected from Red Hat …
```
> feat: Improved UX experience during 'rhc disconnect'

- connect_cmd.go
- disconnect_cmd.go
* Card ID: CCT-1191
* When no error happens and `--format json` is used, then do not output JSON document to `stderr`. It should be printed to `stdout`.
* Open questions:
* Should we output JSON document to `stderr`, when some error happens?
* Should be all errors printed to `stderr` valid JSON documents?
> fix: Do not output machine readable output to stderr

- connect_cmd.go
- rhsm.go
- util.go
* Fix several lint issues discovered in PR #225
* Do not ignore error returned by `Close()`
* Ignore error returned by `Fprintf()`, when `io.Writer` is stdout.
* Simplified some checks
> Fix several lint issues

- integration-tests/test_connect.py
- integration-tests/utils/__init__.py
- main.go
- rhsm.go
* Card ID: CCT-1335
* This CLI option could never been used in production, because configuring satellite server requires more actions. Thus, this CLI option was useless. The connect command should not have any unexpected side effect like changing of configuration file.
* Do not use `--server` in integration tests, because this CLI option was removed from connect command
> feat: Remove hidden CLI option --server from connect command

- conf.go
- connect_cmd.go
- disconnect_cmd.go
- features.go
- go.mod
- go.sum
- interactive.go
- internal/systemd/systemd.go
- logging.go
- main.go
- rhsm.go
- util.go
* Card ID: CCT-239
* github.com/subpop/go-log has been deprecated. This commit replaces its usage throughout the codebase with log/slog from the standard library
* replace `log.Debug`/`log.Info`/etc calls with `slog` counterparts. Calls to `log.Trace()` have been replaced with `slog.Debug()` since no `slog.Trace()` exists
* reference `config.LogLevel` as the currently set log level
* don't exit when an invalid log level is provided
> feat(deps): replace go-log with standard library log/slog

- integration-tests/test_disconnect.py
This test was skipped because it was failing due to open issue CCT-525. I have also updated the expected return code and messages to match the latest upstream developments.
> test: enabling the test as CCT-525 is now fixed

- integration-tests/test_status.py
- rhsm.go
- status_cmd.go
* Card ID: CCT-1526
* When there is some issue e.g. with rhsm.service, then the
"rhc status" should not terminate immediately, but it
should print error for given feature and continue with
printing statuses of other feature
* When `--format json` is used, then errors should be filled
for related features
* Refactored calling `insightStatus()` function to be consistent
with other functions
* When it is not possible to access RHSM D-Bus API due
to e.g. masked `rhsm.service`, then return error as is.
* When yggdrasil wasn't possible to start for various reasons,
then `rhc status` did not print any error at all. The
service was indicated as inactive despite the service was
not present at all. When the service was masked, then
it was also indicated as inactive
* When there is any problem with …
> fix: The "rhc status" should handle errors properly

- integration-tests/utils/__init__.py
test_rhcd_service_restart was failing intermittently at line 109
Race condition where systemctl restart hadn't fully completed before service state was checked
Test was checking service state immediately after restart without waiting for stabilization.
Implemented automatic waiting before checking service state.
> test: Add stability checking to rhcd_service_is_active()

- systemtest/tests/integration/test.sh
This change adds insights-client as a dependency in the testing environment to prevent failures in downstream Jenkins jobs. Testing Farm occasionally provides composed environments without insights-client pre-installed, causing tests to fail. Explicitly installing it ensures our testing remains consistent and reliable.
> test(fix): Install insights-client as test dependency

- integration-tests/test_status.py
This PR fixes docstrings from newly added test cases in `test_status.py` (https://github.com/RedHatInsights/rhc/pull/250)
> fix: Fix docstrings in `test_status.py` so the new test cases can be uploaded to Polarion

- .packit.yml
Since the last time the .packit.yaml file has been updated, RHEL 10 has been released, and RHEL 9 has been branched off 'main'.
This patch ensures we only run tests on Fedora, c10s and el10.
> chore(ci): Set Packit to track RHEL 10

- integration-tests/conftest.py
- integration-tests/test_connect.py
- integration-tests/test_disconnect.py
- integration-tests/test_e2e.py
- integration-tests/test_status.py
- integration-tests/utils/__init__.py
Fixes: https://issues.redhat.com/browse/CCT-1558
This PR removes all `rhcd service` related code and docstrings, as RHEL10 (rhc main branch) only uses the `yggdrasil service`.
> chore: Remove `rhcd service` related code and docstrings

- .github/workflows/go.yml
* Drop testing of golang 1.23 and start to test golang 1.25, because only two last minor versions of Go are supported. More details here: https://go.dev/doc/devel/release#policy
* When you install golang on RHEL-10.0, then 1.24.6 is installed. When you install golang on CentOS Stream 10, then 1.25.0 is installed
> chore(ci): Update GitHub testing matrix of golang

- integration-tests/test_disconnect.py
- integration-tests/test_status.py
- Replaced username/password auth with activation key in tests. This ensures compatibility with satellite environments that don't support basic auth.
> test: Switch integration tests to use activation key authentication

- connect_cmd.go
- disconnect_cmd.go
- internal/rhsm/rhsm.go
- status_cmd.go
* Card ID: CCT-1590
* Moved the rhsm.go to internal/rhsm/rhsm.go
* Renamed some functions to be available as API
* No functional change
> chore: Move rhsm.go to own internal module
